# Generated by Django 5.0.7 on 2024-07-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_latest_articles_web_about_us_web_contact_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Latest_Articles',
            new_name='Web_Latest_Articles',
        ),
    ]
