# Generated by Django 5.0.7 on 2024-07-18 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_latest_articles_web_latest_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web_contact_us',
            old_name='email',
            new_name='phone',
        ),
    ]
