# Generated by Django 5.0.7 on 2024-07-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_email_web_contact_us_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
