# Generated by Django 5.0.7 on 2024-07-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_web_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_contact_us',
            name='phone',
            field=models.CharField(blank=True, default='0000000000', max_length=12, null=True),
        ),
    ]
